HashCube game's specific changes
hashcube/cocos2d-x pull request #11
Opened 2022-10-07 11:29 UTC by rampr

2022-10-07 14:00 UTC, shijasmhd approved these changes

2022-10-08 04:06 UTC, thesayraj approved these changes

2022-10-10 08:20 UTC, anil-kumar07 approved these changes

2022-10-10 09:04 UTC, hatim-developer requested changes

2022-10-10 09:04 UTC, hatim-developer commented on cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxWebView.java
> +        return true;
you are missing some code here @rampr 

https://bitbucket.org/hashcube/frameworks/commits/44b52b199107077e22fe03375e9cf4eea1860707

2022-10-10 09:04 UTC, hatim-developer commented on cocos/storage/local-storage/LocalStorage.cpp
> +    #define USE_USER_DEFAULT_LS
is this right @rampr ? we are not using user default local storage?

2022-10-10 09:05 UTC, rampr commented on cocos/storage/local-storage/LocalStorage.cpp
> +    #define USE_USER_DEFAULT_LS
Let me check

2022-10-10 09:05 UTC, rampr commented on cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxWebView.java
> +        return true;
Thanks @hatim-developer

2022-10-10 09:19 UTC, rampr commented on cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxWebView.java
> +        return true;
This has been missed, will update the changes

2022-10-10 09:20 UTC, rampr commented on cocos/storage/local-storage/LocalStorage.cpp
> +    #define USE_USER_DEFAULT_LS
I have to check, this has been copied over from our version of cocos2d. If this is not used, this is dead code

2022-10-10 11:20 UTC, rampr commented on cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxWebView.java
> +        return true;
Updated

2022-10-10 11:21 UTC, rampr commented on cocos/storage/local-storage/LocalStorage.cpp
> +    #define USE_USER_DEFAULT_LS
@hatim-developer  this is the behaviour for ios.

2022-10-10 12:04 UTC, hatim-developer approved these changes

2022-10-12 03:42 UTC, merged